{% set version = "3.0.0" %}
{% set filename = "apache-arrow-" + version + ".tar.gz" %}
{% set checksum = "73c2cc3be537aa1f3fd9490cfec185714168c9bfd599d23e287ab0cc0558e27a" %}

package:
  name: pyarrow
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://dist.apache.org/repos/dist/release/arrow/arrow-{{ version }}/{{ filename }}
  sha256: {{ checksum }}

build:
  number: 3
  ignore_run_exports:
    - glog
    - snappy
    - grpc-cpp
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - make
  host:
    # directly pin boost-cpp as we also seem to directly include boost symbols
    # in the Python modules.
    - arrow-cpp {{ arrow }}
    - boost-cpp {{ boost }}
    - cython
    - grpc-cpp {{ grpc_cpp }}
    - numpy {{ numpy }}
    - python {{ python }}
    - setuptools {{ setuptools }}
    - setuptools_scm 5.0.2
    - setuptools-scm 5.0.2
    - six {{ six }}
    - uriparser

  run:
    - {{ pin_compatible('arrow-cpp') }}
    - {{ pin_compatible('numpy', lower_bound='1.11') }}
    - boost-cpp {{ boost }}
    - glog
    - pandas
    - python {{ python }}
    - six {{ six }}
    - snappy
    - gflags

test:
  imports:
    - pyarrow
    - pyarrow.dataset
    - pyarrow.flight
    - pyarrow.orc      # [unix]
    - pyarrow.parquet
    - pyarrow.plasma   # [unix]
    - pyarrow.fs
    - pyarrow._s3fs
    - pyarrow._hdfs
  commands:
    - test ! -f ${SP_DIR}/pyarrow/tests/test_array.py                         # [unix]
    - if exist %SP_DIR%/pyarrow/tests/test_array.py exit 1                    # [win]

about:
  home: http://github.com/apache/arrow
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
